---
title: "Processing for CRF"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(knitr)
library(here)
library(dplyr)
library(tidyboot)
library(tidyverse)
library(udpipe)
library(feather)
library(childesr)
library(viridis)
library(markovchain)
library(reshape)
library(entropy)
library(scales)

opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, 
               error = FALSE, cache = TRUE, tidy = FALSE)

theme_set(theme_classic(base_size = 14))
```

```{r load-data, eval = FALSE}
childes_htmm_pdwz <- read_feather(here("data/childes_htmm_15.feather")) 

childes_keep <- childes_htmm_pdwz %>%
  mutate(speaker_role = if_else(speaker_role == "Mother" | speaker_role == "Father",
                                "Parent", speaker_role)) %>%
  group_by(transcript_id, speaker_role) %>%
  summarise(n = n()) %>%
  ungroup() %>%
  complete(speaker_role, transcript_id, fill = list(n = 0)) %>%
  arrange(transcript_id) %>%
  pivot_wider(names_from = "speaker_role", values_from = "n") %>%
  filter(Parent > 10, Target_Child > 10)

childes_htmm_pdwz <- childes_htmm_pdwz %>%
  mutate(speaker_role = if_else(speaker_role == "Mother" | speaker_role == "Father",
                                "Parent", speaker_role)) %>%
  filter(transcript_id %in% childes_keep$transcript_id) %>%
  mutate(age_in_months = floor(target_child_age)) %>%
  filter(age_in_months >= 6) %>%
  mutate(age_bin = cut(age_in_months, breaks = 9))
```

```{r filter-clean, eval = FALSE}
childes_for_crf <- childes_htmm_pdwz %>%
  mutate(gloss = case_when(type == "declarative" ~ paste(gloss, "."),
                           type == "imperative_emphatic" ~ paste(gloss, "!"),
                           str_detect(type, "question") ~ paste(gloss, "?"),
                           type == "trail off" ~ paste(gloss, "?"),
                           TRUE ~ paste(gloss, "."))) %>%
  rename(file_id = transcript_id,
         child_id = target_child_id,
         age_months = age_in_months,
         tokens = gloss,
         pos = part_of_speech,
         speaker = speaker_role) %>%
  mutate(index = 1:n() - 1)

#write_csv(childes_for_crf %>% select(file_id, child_id, age_months, tokens, pos, speaker),
#  here("childes_for_crf.csv"))
```

```{r read-in}
act_codes <- read_csv(here("data/act_codes.csv"))

childes_for_crf <- read_csv(here("data/childes_for_crf.csv")) %>%
  mutate(index = 1:n() - 1)
crf_speech_acts <- read_csv(here("data/crf_speech_acts.csv"))

crf_speech_acts <- crf_speech_acts %>%
  left_join(childes_for_crf, by = "index") %>%
  left_join(act_codes, by = c("y_pred" = "act_code"))

crf_speech_acts %>%
  group_by(speaker.x, y_pred, max_topic) %>%
  count() %>%
  complete(speaker.x, y_pred, max_topic) %>%
  mutate(n = n + 1) %>% # like laplace smoothing
  ungroup() %>% group_by(speaker.x) %>%
  mutate(prob = n/sum(n)) %>%
  ggplot(aes(x=max_topic, y=y_pred, fill=log(prob), group = speaker.x)) + 
  geom_tile() +
  facet_wrap(~speaker.x, scales = "free") +
  viridis::scale_fill_viridis()

ggplot(crf_speech_acts %>%
         mutate(age = floor((age_months.x - 6)/2) * 2 + 6) %>%
         group_by(speaker.x, y_pred, age) %>%
         count(), aes(x = age, y = n, group = y_pred, 
             fill = as.factor(y_pred))) +
  geom_area(position = "fill", color = "black") +
  facet_wrap(~speaker.x) +
  theme(legend.position = "none") + 
  scale_x_continuous(breaks = c(12,24,36,48,60)) +
  labs(x = "Age (months)", y = "Communicative act proportion") 

```


```{r mi}
epsilon = 0.000000000001

crf_topic_joint <- crf_speech_acts %>%
  count(speaker.x, y_pred, max_topic) %>%
  complete(speaker.x, y_pred, max_topic, fill = list(n = 0)) %>%
  mutate(n = n + epsilon,
         prob = n/sum(n)) 

joint_wide <- crf_topic_joint %>%
  count(speaker.x, y_pred, max_topic) %>%
  complete(speaker.x, y_pred, max_topic, fill = list(n = 0)) %>%
  mutate(prob = n/sum(n)) 



get_mis <- function(joint_probs_normed) {
  
  topic_marginal <- joint_probs_normed %>%
    group_by(speaker.x, max_topic) %>%
    summarise(topic_prob = sum(prob)) %>% ungroup()
  
  crf_marginal <- joint_probs_normed %>%
    group_by(speaker.x, y_pred) %>%
    summarise(crf_prob = sum(prob)) %>% ungroup()
  
  all_probs <- joint_probs_normed %>%
    rename(joint_prob = prob) %>%
    left_join(topic_marginal, 
              by = c("speaker.x", "max_topic")) %>%
    left_join(crf_marginal, 
              by = c("speaker.x", "y_pred"))
  
  parent <- all_probs %>%
    filter(speaker.x == "ADU") %>%
    mutate(term = joint_prob * log2(joint_prob/(topic_prob * crf_prob))) %>%
    summarise(mi = sum(term)) %>%
    mutate(type = "parent")
  
  child <- all_probs %>%
    filter(speaker.x == "CHI") %>%
    mutate(term = joint_prob * log2(joint_prob/(topic_prob * crf_prob))) %>%
    summarise(mi = sum(term)) %>%
    mutate(type = "child")

  
  all_mis <- rbind(child, parent)
  return(all_mis)
}

mis <- get_mis(crf_topic_joint)
```

```{r markov-model}
markov_model <- markovchainFit(crf_speech_acts$y_pred)

tmatrix <- as.data.frame(markov_model$estimate@transitionMatrix)

tmatrix_long <- tmatrix %>% rownames_to_column() %>%
  melt() %>%
  dplyr::rename(current_state = rowname, next_state = variable)

tmatrix_long %>%
  ggplot(aes(x=current_state, y=next_state, fill=value)) + 
  geom_tile() +
  scale_fill_viridis()
```

```{r markov-model}
year_one <- crf_speech_acts %>% filter(age_months.x <= 12)
year_two <- crf_speech_acts %>% filter(age_months.x <= 24 & age_months.x > 12)
year_three <- crf_speech_acts %>% filter(age_months.x <= 36 & age_months.x > 24)
three_up <- crf_speech_acts %>% filter(age_months.x > 36)

markov_model_one <- markovchainFit(year_one$y_pred)
markov_model_two <- markovchainFit(year_two$y_pred)
markov_model_three <- markovchainFit(year_three$y_pred)
markov_model_threeup <- markovchainFit(three_up$y_pred)


tmatrix_one <- as.data.frame(markov_model_one$estimate@transitionMatrix) %>% 
  rownames_to_column() %>%
  melt() %>%
  dplyr::rename(current_state = rowname, next_state = variable) %>%
  mutate(age = "< 12")

tmatrix_two <- as.data.frame(markov_model_two$estimate@transitionMatrix) %>% 
  rownames_to_column() %>%
  melt() %>%
  dplyr::rename(current_state = rowname, next_state = variable) %>%
  mutate(age = "< 24")

tmatrix_three <- as.data.frame(markov_model_three$estimate@transitionMatrix) %>% 
  rownames_to_column() %>%
  melt() %>%
  dplyr::rename(current_state = rowname, next_state = variable) %>%
  mutate(age = "< 36")

tmatrix_threeup <- as.data.frame(markov_model_threeup$estimate@transitionMatrix) %>% 
  rownames_to_column() %>%
  melt() %>%
  dplyr::rename(current_state = rowname, next_state = variable) %>%
  mutate(age = "36 +")

tmatrix_all <- rbind(tmatrix_one, tmatrix_two, tmatrix_three, tmatrix_threeup)

tmatrix_all %>%
  ggplot(aes(x=current_state, y=next_state, fill=log(value))) + 
  geom_tile() +
  scale_fill_viridis() +
  facet_wrap(~age)
```

```{r markov-filtered}

common_commacts <- crf_speech_acts %>%
  count(y_pred) %>%
  arrange(desc(n)) %>%
  slice(1:30)

tmatrix_long %>%
  filter(current_state %in% common_commacts$y_pred,
         next_state %in% common_commacts$y_pred) %>%
  ggplot(aes(x=current_state, y=next_state, fill=value)) + 
  geom_tile() +
  scale_fill_viridis()

tmatrix_all %>%
  filter(current_state %in% common_commacts$y_pred,
         next_state %in% common_commacts$y_pred) %>%
  ggplot(aes(x=current_state, y=next_state, fill=value)) + 
  geom_tile() +
  scale_fill_viridis() +
  facet_wrap(~age)

```


```{r commact-probs}

par_child_topic_probs <- crf_speech_acts %>%
  group_by(file_id.x, speaker_code) %>%
  count(y_pred) %>%
  ungroup() %>%
  complete(file_id.x, speaker_code, y_pred, fill = list(n = 0)) %>% 
  group_by(file_id.x, speaker_code) %>%
  mutate(sum = sum(n)) %>% 
  ungroup() %>%
  mutate(prob = n / sum) %>% 
  select(file_id.x, speaker_code, y_pred, prob) %>%
  pivot_wider(names_from = speaker_code, values_from = prob)

```

```{r info-destroying}

unintelligible <- crf_speech_acts %>%
  group_by(file_id.x) %>%
  mutate(speech_act = y_pred, prev_act = lag(speech_act), next_act = lead(speech_act)) %>%
  ungroup() %>%
  filter(speech_act == "YY", speaker_code == "CHI", prev_act %in% common_commacts$y_pred,
         next_act %in% common_commacts$y_pred) 


unintelligible %>%
  group_by(prev_act) %>%
  count(next_act) %>%
  mutate(prob = n/sum(n)) %>%
  ggplot(aes(x=prev_act, y=next_act, fill=prob)) + 
  geom_tile() +
  scale_fill_viridis()

unintelligible %>%
  group_by(prev_act) %>%
  count(next_act) %>%
  mutate(prob = n/sum(n)) %>%
  ungroup() %>%
  ggplot(aes(x=prev_act, y=next_act, fill=prob)) + 
  geom_tile() +
  scale_fill_viridis()

prev_next_ent <- unintelligible %>%
  group_by(prev_act) %>%
  count(next_act) %>%
  mutate(prob = n/sum(n)) %>%
  mutate(entropy = entropy(prob)) %>%
  ungroup() %>% 
  summarise(mean(entropy))

yy_next_ent <- unintelligible %>%
  count(next_act) %>%
  mutate(prob = n/sum(n)) %>%
  summarise(entropy = entropy(prob)) 

crf_speech_acts %>%
  group_by(file_id.x) %>%
  mutate(speech_act = y_pred, prev_act = lag(speech_act), next_act = lead(speech_act)) %>%
  ungroup() %>%
  group_by(prev_act) %>%
  count(next_act) %>%
  mutate(prob = n/sum(n)) %>%
  mutate(entropy = entropy(prob)) %>%
  ungroup() %>% 
  summarise(mean(entropy))

crf_speech_acts %>%
  group_by(file_id.x) %>%
  mutate(speech_act = y_pred, prev_act = lag(speech_act), next_act = lead(speech_act)) %>%
  ungroup() %>%
  group_by(speech_act) %>%
  count(next_act) %>%
  mutate(prob = n/sum(n)) %>%
  mutate(entropy = entropy(prob)) %>%
  ungroup() %>% 
  summarise(mean(entropy))

crf_speech_acts %>%
  group_by(file_id.x) %>%
  mutate(speech_act = y_pred, prev_act = lag(speech_act), next_act = lead(speech_act)) %>%
  ungroup() %>%
  group_by(age_months.x, prev_act, speech_act) %>%
  count(next_act) %>%
  mutate(prob = n/sum(n)) %>%
  mutate(entropy = entropy(prob)) %>%
  ungroup() %>% 
  group_by(age_months.x) %>%
  summarise(mean(entropy))
  
  
```



```{r crf-for-hmm-threes}
threes <- crf_speech_acts %>%
  filter(age_months.x > 36, age_months.x < 48)

all_letters <- tibble(letter = c(paste(LETTERS, sep = ","), paste(letters, sep = ",")))

commacts_dict_threes <- threes %>%
  count(y_pred) %>%
  mutate(y_pred = if_else(n < 40, "RARE", y_pred)) %>% # adjust so you end up with 52 or fewer types
  group_by(y_pred) %>%
  summarise(n = sum(n)) %>% ungroup() %>%
  arrange(desc(n)) 


all_letters <- slice_head(all_letters, n = nrow(commacts_dict_threes)+1)
commacts_dict_threes <- commacts_dict_threes %>% add_row(y_pred = "END")
commacts_dict_threes$token <- all_letters$letter

last_utt <- threes %>%
   group_by(file_id.x) %>%
   summarise(index = max(index)) %>%
   mutate(index = index + 1,
          y_pred = "END") 
  
threes <- threes %>%
  bind_rows(last_utt) %>%
  arrange(file_id.x, index) %>%
  mutate(commact = if_else(y_pred %in% commacts_dict_threes$y_pred, y_pred, "RARE")) %>%
  left_join(commacts_dict_threes, by = c("commact" = "y_pred")) 

max <- threes %>% distinct(token) %>% arrange(desc(token))
na <- threes %>% filter(is.na(token))

n_tokens = nrow(threes)
n_types = threes %>% distinct(token) %>% nrow()

seq = str_remove_all(toString(as.list(threes$token)), ", ")

#write.csv(seq, here("data/threes_crf_for_hmm.txt"),
#         row.names = FALSE)

#write_csv(commacts_dict, here("data/dict_three_commacts.csv"))

```

```{r crf-for-hmm}
commacts_dict <- crf_speech_acts %>%
  count(y_pred) %>%
  group_by(y_pred) %>%
  summarise(n = sum(n)) %>% ungroup() %>%
  arrange(desc(n)) 

commacts_dict <- commacts_dict %>% 
  add_row(y_pred = "END") %>%
  mutate(speech_act_id = row_number() - 1)

last_utt <- crf_speech_acts %>%
   group_by(file_id.x) %>%
   summarise(index = max(index)) %>%
   mutate(index = index + 1,
          y_pred = "END") 
  
speech_acts_for_hmm <- crf_speech_acts %>%
  bind_rows(last_utt) %>%
  arrange(file_id.x, index) %>%
  left_join(commacts_dict %>% select(y_pred, speech_act_id)) 

# just check to make sure things look good
max <- speech_acts_for_hmm %>% distinct(speech_act_id) %>% arrange(desc(speech_act_id))
na <- speech_acts_for_hmm %>% filter(is.na(speech_act_id))

# get num tokens and types to put in HMM
n_tokens = nrow(speech_acts_for_hmm)
n_types = speech_acts_for_hmm %>% distinct(speech_act_id) %>% nrow()

#write.csv(speech_acts_for_hmm %>% select(speech_act_id), here("data/childes_crf_for_hmm.txt"),
#         row.names = FALSE)

#write_csv(commacts_dict, here("data/childes_commacts_dict.csv"))

```

```{r read-hmm}
reconstruction <- read_csv(here("data/threes_reconstruction.txt"))
three_crf_hmm <- cbind(threes, reconstruction)

three_crf_hmm <- three_crf_hmm %>%
  filter(commact != "END")

#write_csv(three_crf_hmm, here("data/three_crf_hmm.csv"))

reconstruction <- read_csv(here("data/childes_crf_10.csv"))
full_crf_hmm <- cbind(speech_acts_for_hmm, reconstruction)


#write_csv(full_crf_hmm, here("data/full_crf_hmm.csv"))
```

```{r}
three_crf_hmm <- read_csv(here("data/three_crf_hmm.csv"))

three_crf_hmm %>%
  count(commact, reconstruction) %>%
  group_by(commact) %>%
  mutate(prob = n/sum(n)) %>%
  ungroup() %>%
  ggplot(aes(x=commact, y=reconstruction, fill=prob)) + 
  geom_tile() +
  scale_fill_viridis() 

three_crf_hmm %>%
  group_by(file_id.y) %>%
  mutate(next_state = lead(reconstruction)) %>%
  ungroup() %>%
  count(reconstruction, next_state) %>%
  group_by(reconstruction) %>%
  mutate(prob = n/sum(n)) %>%
  ungroup() %>%
  ggplot(aes(x=reconstruction, y=next_state, fill=prob)) + 
  geom_tile() +
  scale_fill_viridis() 

three_crf_hmm %>%
  group_by(file_id.y) %>%
  mutate(next_state = lead(reconstruction)) %>%
  ungroup() %>%
  group_by(age_bin) %>%
  count(reconstruction, next_state) %>%
  ungroup() %>%
  group_by(age_bin, reconstruction) %>%
  mutate(prob = n/sum(n)) %>%
  ungroup() %>%
  ggplot(aes(x=reconstruction, y=next_state, fill=prob)) + 
  geom_tile() +
  scale_fill_viridis() +
  facet_wrap(~age_bin) 

ggplot(three_crf_hmm %>%
         mutate(age = floor((age_months.x - 6)/2) * 2 + 6) %>%
         group_by(speaker.x, reconstruction, age) %>%
         count(), aes(x = age, y = n, group = reconstruction, 
             fill = as.factor(reconstruction))) +
  geom_area(position = "fill", color = "black") +
  facet_wrap(~speaker.x) +
  theme(legend.position = "none") + 
  scale_x_continuous(breaks = c(12,24,36,48,60)) +
  labs(x = "Age (months)", y = "Communicative act proportion") 

three_crf_hmm %>%
  filter(speaker_code %in% c("CHI", "MOT")) %>%
  count(speaker_code, reconstruction) %>%
  ggplot(aes(fill = as.factor(reconstruction), y = n, x = speaker_code)) +
  geom_bar(position="fill", stat = "identity") 

sample_threes <- three_crf_hmm %>% group_by(reconstruction) %>% slice_sample(n=10) %>%
  select(tokens.y, reconstruction)


```

```{r}
full_crf_hmm <- read_csv(here("data/full_crf_hmm.csv"))

top_acts <- full_crf_hmm %>%
  filter(!is.na(meaning)) %>%
  count(reconstruction, meaning) %>%
  group_by(reconstruction) %>%
  mutate(prob = n/sum(n)) %>%
  arrange(desc(prob)) %>%
  slice(1:3) %>%
  ungroup()

full_crf_hmm %>%
  count(y_pred, reconstruction) %>%
  group_by(y_pred) %>%
  mutate(prob = n/sum(n)) %>%
  ungroup() %>%
  ggplot(aes(x=y_pred, y=reconstruction, fill=prob)) + 
  geom_tile() +
  scale_fill_viridis() 

full_crf_hmm %>%
  count(y_pred, reconstruction) %>%
  group_by(y_pred) %>%
  mutate(prob = n/sum(n)) %>%
  ungroup() %>%
  ggplot(aes(fill=y_pred, y=prob, x=reconstruction)) + 
    geom_bar(position="stack", stat="identity")

full_crf_hmm %>%
  filter(y_pred != "END") %>%
  group_by(file_id.y) %>%
  mutate(next_state = lead(reconstruction)) %>%
  ungroup() %>%
  count(reconstruction, next_state) %>%
  group_by(reconstruction) %>%
  mutate(prob = n/sum(n)) %>%
  ungroup() %>%
  ggplot(aes(x=reconstruction, y=next_state, fill=prob)) + 
  geom_tile() +
  scale_fill_viridis() +
  scale_x_continuous(breaks = pretty_breaks()) +
  scale_y_continuous(breaks = pretty_breaks())

full_crf_hmm %>%
  group_by(file_id.y) %>%
  mutate(next_state = lead(reconstruction)) %>%
  ungroup() %>%
  group_by(age_bin) %>%
  count(reconstruction, next_state) %>%
  ungroup() %>%
  group_by(age_bin, reconstruction) %>%
  mutate(prob = n/sum(n)) %>%
  ungroup() %>%
  ggplot(aes(x=reconstruction, y=next_state, fill=prob)) + 
  geom_tile() +
  scale_fill_viridis() +
  facet_wrap(~age_bin)

ggplot(full_crf_hmm %>%
         filter(!is.na(speaker.x)) %>%
         mutate(age = floor((age_months.x - 6)/2) * 2 + 6) %>%
         group_by(speaker.x, reconstruction, age) %>%
         count(), aes(x = age, y = n, group = reconstruction, 
             fill = as.factor(reconstruction))) +
  geom_area(position = "fill", color = "black") +
  facet_wrap(~speaker.x) +
  scale_x_continuous(breaks = c(12,24,36,48,60)) +
  labs(x = "Age (months)", y = "Communicative act proportion") 

three_crf_hmm %>%
  filter(speaker_code %in% c("CHI", "MOT")) %>%
  count(speaker_code, reconstruction) %>%
  ggplot(aes(fill = as.factor(reconstruction), y = n, x = speaker_code)) +
  geom_bar(position="fill", stat = "identity") 

sample_threes <- three_crf_hmm %>% group_by(reconstruction) %>% slice_sample(n=10) %>%
  select(tokens.y, reconstruction)


```
