---
title: "entropy_analyses"
author: "Claire Bergey and Zoe Marshall"
date: "7/23/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(dplyr)
library(here)
library(feather)
library(tidyverse)
library(plotly)
library(reticulate)
library(entropy)
library(tidyboot)
library(randomizeR)
library(purrr)
library(gsl)
library(reticulate)
use_condaenv("r-reticulate")
```


```{r read_feather}
framed_childes <- 
  read_feather(here("data/childes_parsed_frames.feather")) %>%
  mutate(transcript_id = as.numeric(transcript_id),
         utterance_order = as.numeric(utterance_order),
         target_child_age = as.numeric(target_child_age)) %>%
  filter(target_child_age <= 60) %>%
  filter(!str_detect(gloss, "yyy"),!str_detect(gloss, "xxx"),
         !is.na(target_child_age)) %>%
  mutate(speaker_code = ifelse(speaker_code == "MOM", "MOT", speaker_code),
         speaker_code = ifelse(speaker_code == "DAD", "FAT", speaker_code))
```

```{r filter}
cleaned_childes <- framed_childes %>%
  mutate(speaker_code = ifelse(speaker_code == "MOT" | speaker_code == "FAT", "PAR", speaker_code))

valid_transcripts <- cleaned_childes %>%
  filter(speaker_code == "CHI" | speaker_code == "PAR") %>%
  group_by(transcript_id, speaker_code) %>% count() %>%
  filter(n > 100) %>%
  ungroup() %>% group_by(transcript_id) %>% count() %>%
  filter(n == 2)
```

```{r clean}
cleaned_childes <- cleaned_childes %>% 
  filter(speaker_code == "CHI"| speaker_code == "PAR") %>% 
  mutate(age_in_months = floor(target_child_age)) %>% 
  filter(transcript_id %in% valid_transcripts$transcript_id) 

count_vector_frame <- cleaned_childes %>% 
  group_by(utt_parse, transcript_id, speaker_code) %>%
  count() %>% ungroup()

count_vector_gloss <- cleaned_childes %>%
  group_by(gloss, transcript_id, speaker_code) %>%
  count() %>% ungroup()
```

```{r}
counts_wide <- count_vector_frame %>%
  pivot_wider(names_from = "utt_parse", values_from = "n", values_fill = 0) %>%
  mutate(name = paste0(transcript_id, speaker_code)) %>%
  select(name, everything()) %>%
  select(-transcript_id, -speaker_code) 

row.names(counts_wide) <- counts_wide$name

transcripts_list <- setNames(as.list(as.data.frame(t(counts_wide %>% select(-name)))), rownames(counts_wide))
```

```{python}
import ndd

entropies_dict = {}

for key, value in r.transcripts_list.items():
  entropies_dict[key] = ndd.entropy(value)
```

```{r}
entropies <- py$entropies_dict

entropy_vector_frame <- count_vector_frame %>% 
  group_by(transcript_id, speaker_code_2) %>% 
  mutate(entropy = entropy(n)) %>%
  summarise(entropy = first(entropy), age = first(basic_age))

entropy_vector_gloss <- count_vector_gloss %>% 
  group_by(transcript_id, speaker_code_2) %>% 
  mutate(entropy = entropy(n)) %>%
  summarise(entropy = first(entropy), age = first(basic_age))
```

```{r rondomize}
entropy_rand_frame <- entropy_vector_frame %>%
  group_by(age, speaker_code_2) %>%
  mutate(entropy_random = entropy[sample(row_number())]) %>%
  ungroup()

entropy_rand_gloss <- entropy_vector_gloss %>%
  group_by(age, speaker_code_2) %>%
  mutate(entropy_random = entropy[sample(row_number())]) %>%
  ungroup()
```


```{r}
entropy_vector_frame <- count_vector_frame %>% 
  group_by(transcript_id, speaker_code_2) %>% 
  mutate(entropy = entropy.NSB(.$n, 
    CMD = here("childlanguageinfo/nsb-entropy-1.14/build/nsb-entropy"))) %>%
  summarise(entropy = first(entropy), age = first(basic_age))

entropy_vector_gloss <- count_vector_gloss %>% 
  group_by(transcript_id, speaker_code_2) %>% 
  mutate(entropy = entropy(n, CMD = here("nsb-entropy-1.14/nsb.entropy.R"))) %>%
  summarise(entropy = first(entropy), age = first(basic_age))
```
```{r rondomize}
entropy_rand_frame <- entropy_vector_frame %>%
  group_by(age, speaker_code_2) %>%
  mutate(entropy_random = entropy[sample(row_number())]) %>%
  ungroup()

entropy_rand_gloss <- entropy_vector_gloss %>%
  group_by(age, speaker_code_2) %>%
  mutate(entropy_random = entropy[sample(row_number())]) %>%
  ungroup()
```


```{r graph1}
entropy_rand_frame %>%
  ggplot(aes(age, entropy_random, color = speaker_code_2)) +
  geom_point(alpha = 0.8) +
  geom_smooth() +
  geom_point(data = entropy_rand_gloss, alpha = 0.8) +
  geom_smooth(data = entropy_rand_gloss) +
  ylab("Entropy") +
  xlab("Exact Age") +
  ggtitle("Entropy of Frames and Gloss") +
  theme_classic()
```



```{r}
entropy_rand_frame %>%
  pivot_longer(cols = c(entropy, entropy_random), names_to = "is_random", values_to = "entropy") %>%
  pivot_wider(values_from = entropy, names_from = speaker_code_2) %>%
  ggplot(aes(x = PAR, y = CHI, color = age)) +
  geom_point() +
  geom_smooth(method = "lm") +
  facet_wrap(~is_random)
```
