---
title: "shuffled_entropy"
author: "Zoe Marshall"
date: "7/23/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(plyr)
library(dplyr)
library(here)
library(feather)
library(tidyverse)
library(plotly)
library(reticulate)
library(entropy)
library(tidyboot)
library(randomizeR)
library(purrr)
library(gsl)
library(hash)
use_virtualenv("r-reticulate")
```


```{r readfeather}
framed_childes <- 
  read_feather(here("childes_parsed_frames.feather")) %>%
  mutate(transcript_id = as.numeric(transcript_id),
         utterance_order = as.numeric(utterance_order),
         target_child_age = as.numeric(target_child_age)) %>%
  filter(target_child_age <= 60) %>%
  filter(!str_detect(gloss, "yyy"),!str_detect(gloss, "xxx"),
         !is.na(target_child_age)) %>%
  mutate(speaker_code = ifelse(speaker_code == "MOM", "MOT", speaker_code),
         speaker_code = ifelse(speaker_code == "DAD", "FAT", speaker_code))
```

```{r filter}
par_child <- framed_childes %>%
  mutate(speaker_code_2 = ifelse(speaker_code == "MOT" | speaker_code == "FAT", "PAR", speaker_code))

valid_transcripts <- par_child %>%
  filter(speaker_code_2 == "CHI" | speaker_code_2 == "PAR") %>%
  group_by(transcript_id) %>%
  count() %>%
  filter(n > 100)

more_valid_transcripts <- par_child %>%
  filter(speaker_code_2 == "CHI" | speaker_code_2 == "PAR") %>%
  group_by(speaker_code_2, transcript_id) %>%
  count() %>%
  filter(n > 10)

valid_utt <- framed_childes %>%
  group_by(utt_parse) %>%
  count() %>%
  filter(n > 300)
```

```{r clean}
children_with_ages <- par_child %>% 
  filter(speaker_code_2=="CHI"|speaker_code_2=="PAR") %>% 
  mutate(basic_age=floor(target_child_age)) %>% 
  filter(transcript_id %in% valid_transcripts$transcript_id) %>%
  filter(transcript_id %in% more_valid_transcripts$transcript_id) %>%
  filter(utt_parse %in% valid_utt$utt_parse)

count_vector_frame <- children_with_ages %>% 
  group_by(utt_parse, basic_age, transcript_id, speaker_code_2) %>%
  count()

count_vector_gloss <- children_with_ages %>%
  group_by(gloss, basic_age, transcript_id, speaker_code_2) %>%
  count()
```

```{r entropy}
y = c(4, 2, 3, 0, 2, 4, 0, 0, 2, 1, 1) 
entropy.NSB(y, CMD = here("nsb-entropy-1.14/build/nsb-entropy"))
```

```{r}
z <- count_vector_frame %>%
  filter(transcript_id == 6550 | transcript_id == 2952 | transcript_id == 8444) %>%
  group_by(transcript_id, speaker_code_2) %>%
  summarize(entropy = entropy.NSB(.$n, CMD = here("nsb-entropy-1.14/build/nsb-entropy")))


o <- count_vector_frame %>%
  filter(transcript_id == 6550 | transcript_id == 2952 | transcript_id == 8444) %>%
  aggregate(by = c(transcript_id, speaker_code_2), FUN = entropy.NSB(n, CMD =                                                        here("childlanguageinfo/nsb-entropy-1.14/build/nsb-entropy")))

setwd("~/Desktop/childesResearch2020/childlanguageinfo")



x <- count_vector_frame %>%
  filter(transcript_id == 6550 | transcript_id == 2952 | transcript_id == 8444) %>%
  filter(!is.na(n) | !is.null(n)) %>%
  dlply(.variables = c("transcript_id", "speaker_code_2")) %>% 
  purrr::transpose()

nsb_entropy <- function(l) {
  map(l, entropy.NSB(l, CMD = here("nsb-entropy-1.14/build/nsb-entropy")))
}


map(x$n, nsb_entropy)

map(entropy_list, nsb_entropy)



df <- count_vector_frame %>% 
  mutate(unique_grouping = paste0(transcript_id, speaker_code_2))

entropy_list <- df %>%
  pivot_wider(names_from = "utt_parse", values_from = "n") 

entropy_list[is.na(entropy_list)] <- 0

entropy_list <- entropy_list %>%
  select(-basic_age, -speaker_code_2, -transcript_id)
  

for(i in 1:116) {
  if (length(entropy_list[[i]]) != 1) {
    entropy_list[[i]] <- entropy.NSB(entropy_list[[i]], CMD = here("nsb-entropy-1.14/build/nsb-entropy"))
  }
}

for(i in 118:843) {
  if (length(entropy_list[[i]]) != 1) {
    entropy_list[[i]] <- entropy.NSB(entropy_list[[i]], CMD = here("nsb-entropy-1.14/build/nsb-entropy"))
  }
}

for(i in 845:860) {
  if (length(entropy_list[[i]]) != 1) {
    entropy_list[[i]] <- entropy.NSB(entropy_list[[i]], CMD = here("nsb-entropy-1.14/build/nsb-entropy"))
  }
}

for(i in 862:900) {
  if (length(entropy_list[[i]]) != 1) {
    entropy_list[[i]] <- entropy.NSB(entropy_list[[i]], CMD = here("nsb-entropy-1.14/build/nsb-entropy"))
  }
}

for(i in 901:987) {
  if (length(entropy_list[[i]]) != 1) {
    entropy_list[[i]] <- entropy.NSB(entropy_list[[i]], CMD = here("nsb-entropy-1.14/build/nsb-entropy"))
  }
}

for(i in 989:1021) {
  if (length(entropy_list[[i]]) != 1) {
    entropy_list[[i]] <- entropy.NSB(entropy_list[[i]], CMD = here("nsb-entropy-1.14/build/nsb-entropy"))
  }
}

for(i in 1023:1049) {
  if (length(entropy_list[[i]]) != 1) {
    entropy_list[[i]] <- entropy.NSB(entropy_list[[i]], CMD = here("nsb-entropy-1.14/build/nsb-entropy"))
  }
}

for(i in 1051:1057) {
  if (length(entropy_list[[i]]) != 1) {
    entropy_list[[i]] <- entropy.NSB(entropy_list[[i]], CMD = here("nsb-entropy-1.14/build/nsb-entropy"))
  }
}

for(i in 1059:1095) {
  if (length(entropy_list[[i]]) != 1) {
    entropy_list[[i]] <- entropy.NSB(entropy_list[[i]], CMD = here("nsb-entropy-1.14/build/nsb-entropy"))
  }
}

for(i in 1097:1205) {
  if (length(entropy_list[[i]]) != 1) {
    entropy_list[[i]] <- entropy.NSB(entropy_list[[i]], CMD = here("nsb-entropy-1.14/build/nsb-entropy"))
  }
}

for(i in 1207:1259) {
  if (length(entropy_list[[i]]) != 1) {
    entropy_list[[i]] <- entropy.NSB(entropy_list[[i]], CMD = here("nsb-entropy-1.14/build/nsb-entropy"))
  }
}

for(i in 1261:1284) {
  if (length(entropy_list[[i]]) != 1) {
    entropy_list[[i]] <- entropy.NSB(entropy_list[[i]], CMD = here("nsb-entropy-1.14/build/nsb-entropy"))
  }
}

for(i in 1286:1300) {
  if (length(entropy_list[[i]]) != 1) {
    entropy_list[[i]] <- entropy.NSB(entropy_list[[i]], CMD = here("nsb-entropy-1.14/build/nsb-entropy"))
  }
}

entropy_list[[1260]] <- entropy.NSB(entropy_list[[1260]], CMD = here("nsb-entropy-1.14/build/nsb-entropy"))

# can't do a list size of 1
```

```{python}
import ndd
counts = [4, 12, 4, 5, 3, 1, 5, 1, 2, 2, 2, 2, 11, 3, 4, 12, 12, 1, 2]
ndd.entropy(counts, k=100)

for value in r.entropy_list.values():
  print(value)

r.entropy_list.values()

```

```{r}
entropy_vector_frame <- count_vector_frame %>% 
  group_by(transcript_id, speaker_code_2) %>% 
  mutate(entropy = entropy.NSB(.$n, 
    CMD = here("childlanguageinfo/nsb-entropy-1.14/build/nsb-entropy"))) %>%
  summarise(entropy = first(entropy), age = first(basic_age))

entropy_vector_gloss <- count_vector_gloss %>% 
  group_by(transcript_id, speaker_code_2) %>% 
  mutate(entropy = entropy(n, CMD = here("nsb-entropy-1.14/nsb.entropy.R"))) %>%
  summarise(entropy = first(entropy), age = first(basic_age))
```
```{r rondomize}
entropy_rand_frame <- entropy_vector_frame %>%
  group_by(age, speaker_code_2) %>%
  mutate(entropy_random = entropy[sample(row_number())]) %>%
  ungroup()

entropy_rand_gloss <- entropy_vector_gloss %>%
  group_by(age, speaker_code_2) %>%
  mutate(entropy_random = entropy[sample(row_number())]) %>%
  ungroup()
```


```{r graph1}
entropy_rand_frame %>%
  ggplot(aes(age, entropy_random, color = speaker_code_2)) +
  geom_point(alpha = 0.8) +
  geom_smooth() +
  geom_point(data = entropy_rand_gloss, alpha = 0.8) +
  geom_smooth(data = entropy_rand_gloss) +
  ylab("Entropy") +
  xlab("Exact Age") +
  ggtitle("Entropy of Frames and Gloss") +
  theme_classic()
```



```{r}
entropy_rand_frame %>%
  pivot_longer(cols = c(entropy, entropy_random), names_to = "is_random", values_to = "entropy") %>%
  pivot_wider(values_from = entropy, names_from = speaker_code_2) %>%
  ggplot(aes(x = PAR, y = CHI, color = age)) +
  geom_point() +
  geom_smooth(method = "lm") +
  facet_wrap(~is_random)
```
